CREATE DATABASE IF NOT EXISTS web;

USE web;

CREATE TABLE students
(
    id    INT PRIMARY KEY AUTO_INCREMENT,
    name  VARCHAR(255) NOT NULL,
    age   INT          NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(11)  NOT NULL
);